// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/gopherkeeper.proto

package gopherkeeperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED RecordType = 0
	RecordType_RECORD_TYPE_CREDENTIALS RecordType = 1
	RecordType_RECORD_TYPE_CARD        RecordType = 2
	RecordType_RECORD_TYPE_TEXT        RecordType = 3
	RecordType_RECORD_TYPE_BINARY      RecordType = 4
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_CREDENTIALS",
		2: "RECORD_TYPE_CARD",
		3: "RECORD_TYPE_TEXT",
		4: "RECORD_TYPE_BINARY",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED": 0,
		"RECORD_TYPE_CREDENTIALS": 1,
		"RECORD_TYPE_CARD":        2,
		"RECORD_TYPE_TEXT":        3,
		"RECORD_TYPE_BINARY":      4,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gopherkeeper_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_api_gopherkeeper_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type User struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Login     string                 `protobuf:"bytes,2,opt,name=login,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_gopherkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *User) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *User) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *User) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *User) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *User) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        int64
	Login     string
	CreatedAt *timestamppb.Timestamp
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

type RegisterRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_gopherkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *RegisterResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *RegisterResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *RegisterResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

type LoginRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

type LoginResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User        *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	xxx_hidden_AccessToken string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_gopherkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *LoginResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *LoginResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *LoginResponse) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *LoginResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *LoginResponse) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *LoginResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

func (x *LoginResponse) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User        *User
	AccessToken string
	ExpiresAt   *timestamppb.Timestamp
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

type CurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserRequest) Reset() {
	*x = CurrentUserRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserRequest) ProtoMessage() {}

func (x *CurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CurrentUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CurrentUserRequest_builder) Build() *CurrentUserRequest {
	m0 := &CurrentUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CurrentUserResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CurrentUserResponse) Reset() {
	*x = CurrentUserResponse{}
	mi := &file_api_gopherkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserResponse) ProtoMessage() {}

func (x *CurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CurrentUserResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *CurrentUserResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *CurrentUserResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *CurrentUserResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type CurrentUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 CurrentUserResponse_builder) Build() *CurrentUserResponse {
	m0 := &CurrentUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

type RecordMetadata struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Type      RecordType             `protobuf:"varint,2,opt,name=type,proto3,enum=gopherkeeper.v1.RecordType"`
	xxx_hidden_Title     string                 `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Revision  int64                  `protobuf:"varint,4,opt,name=revision,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecordMetadata) Reset() {
	*x = RecordMetadata{}
	mi := &file_api_gopherkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMetadata) ProtoMessage() {}

func (x *RecordMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordMetadata) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *RecordMetadata) GetType() RecordType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *RecordMetadata) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *RecordMetadata) GetRevision() int64 {
	if x != nil {
		return x.xxx_hidden_Revision
	}
	return 0
}

func (x *RecordMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *RecordMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *RecordMetadata) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *RecordMetadata) SetType(v RecordType) {
	x.xxx_hidden_Type = v
}

func (x *RecordMetadata) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *RecordMetadata) SetRevision(v int64) {
	x.xxx_hidden_Revision = v
}

func (x *RecordMetadata) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *RecordMetadata) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *RecordMetadata) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *RecordMetadata) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *RecordMetadata) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *RecordMetadata) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type RecordMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        string
	Type      RecordType
	Title     string
	Revision  int64
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 RecordMetadata_builder) Build() *RecordMetadata {
	m0 := &RecordMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Revision = b.Revision
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type CredentialsPayload struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_Url      string                 `protobuf:"bytes,3,opt,name=url,proto3"`
	xxx_hidden_Metadata string                 `protobuf:"bytes,4,opt,name=metadata,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CredentialsPayload) Reset() {
	*x = CredentialsPayload{}
	mi := &file_api_gopherkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsPayload) ProtoMessage() {}

func (x *CredentialsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CredentialsPayload) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *CredentialsPayload) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *CredentialsPayload) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *CredentialsPayload) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *CredentialsPayload) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *CredentialsPayload) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *CredentialsPayload) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *CredentialsPayload) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

type CredentialsPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
	Url      string
	Metadata string
}

func (b0 CredentialsPayload_builder) Build() *CredentialsPayload {
	m0 := &CredentialsPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type CardPayload struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      string                 `protobuf:"bytes,1,opt,name=number,proto3"`
	xxx_hidden_Cardholder  string                 `protobuf:"bytes,2,opt,name=cardholder,proto3"`
	xxx_hidden_ExpiryMonth *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=expiry_month,json=expiryMonth,proto3"`
	xxx_hidden_ExpiryYear  *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=expiry_year,json=expiryYear,proto3"`
	xxx_hidden_Cvv         string                 `protobuf:"bytes,5,opt,name=cvv,proto3"`
	xxx_hidden_Metadata    string                 `protobuf:"bytes,6,opt,name=metadata,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardPayload) Reset() {
	*x = CardPayload{}
	mi := &file_api_gopherkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPayload) ProtoMessage() {}

func (x *CardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardPayload) GetNumber() string {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return ""
}

func (x *CardPayload) GetCardholder() string {
	if x != nil {
		return x.xxx_hidden_Cardholder
	}
	return ""
}

func (x *CardPayload) GetExpiryMonth() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_ExpiryMonth
	}
	return nil
}

func (x *CardPayload) GetExpiryYear() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_ExpiryYear
	}
	return nil
}

func (x *CardPayload) GetCvv() string {
	if x != nil {
		return x.xxx_hidden_Cvv
	}
	return ""
}

func (x *CardPayload) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *CardPayload) SetNumber(v string) {
	x.xxx_hidden_Number = v
}

func (x *CardPayload) SetCardholder(v string) {
	x.xxx_hidden_Cardholder = v
}

func (x *CardPayload) SetExpiryMonth(v *wrapperspb.Int32Value) {
	x.xxx_hidden_ExpiryMonth = v
}

func (x *CardPayload) SetExpiryYear(v *wrapperspb.Int32Value) {
	x.xxx_hidden_ExpiryYear = v
}

func (x *CardPayload) SetCvv(v string) {
	x.xxx_hidden_Cvv = v
}

func (x *CardPayload) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *CardPayload) HasExpiryMonth() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiryMonth != nil
}

func (x *CardPayload) HasExpiryYear() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiryYear != nil
}

func (x *CardPayload) ClearExpiryMonth() {
	x.xxx_hidden_ExpiryMonth = nil
}

func (x *CardPayload) ClearExpiryYear() {
	x.xxx_hidden_ExpiryYear = nil
}

type CardPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number      string
	Cardholder  string
	ExpiryMonth *wrapperspb.Int32Value
	ExpiryYear  *wrapperspb.Int32Value
	Cvv         string
	Metadata    string
}

func (b0 CardPayload_builder) Build() *CardPayload {
	m0 := &CardPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Number = b.Number
	x.xxx_hidden_Cardholder = b.Cardholder
	x.xxx_hidden_ExpiryMonth = b.ExpiryMonth
	x.xxx_hidden_ExpiryYear = b.ExpiryYear
	x.xxx_hidden_Cvv = b.Cvv
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type TextPayload struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text     string                 `protobuf:"bytes,1,opt,name=text,proto3"`
	xxx_hidden_Metadata string                 `protobuf:"bytes,2,opt,name=metadata,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_api_gopherkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextPayload) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *TextPayload) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *TextPayload) SetText(v string) {
	x.xxx_hidden_Text = v
}

func (x *TextPayload) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

type TextPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text     string
	Metadata string
}

func (b0 TextPayload_builder) Build() *TextPayload {
	m0 := &TextPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type BinaryPayload struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename    string                 `protobuf:"bytes,1,opt,name=filename,proto3"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
	xxx_hidden_Metadata    string                 `protobuf:"bytes,3,opt,name=metadata,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BinaryPayload) Reset() {
	*x = BinaryPayload{}
	mi := &file_api_gopherkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryPayload) ProtoMessage() {}

func (x *BinaryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryPayload) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *BinaryPayload) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *BinaryPayload) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *BinaryPayload) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *BinaryPayload) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *BinaryPayload) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *BinaryPayload) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BinaryPayload) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type BinaryPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filename string
	// data объявлено optional, чтобы отличать отсутствующее поле от переданного пустого файла.
	Data     []byte
	Metadata string
}

func (b0 BinaryPayload_builder) Build() *BinaryPayload {
	m0 := &BinaryPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filename = b.Filename
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Data = b.Data
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

// RecordPayload содержит полезную нагрузку ровно одного типа записи.
type RecordPayload struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value isRecordPayload_Value  `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordPayload) Reset() {
	*x = RecordPayload{}
	mi := &file_api_gopherkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPayload) ProtoMessage() {}

func (x *RecordPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordPayload) GetCredentials() *CredentialsPayload {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*recordPayload_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *RecordPayload) GetCard() *CardPayload {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*recordPayload_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *RecordPayload) GetText() *TextPayload {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*recordPayload_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *RecordPayload) GetBinary() *BinaryPayload {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*recordPayload_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *RecordPayload) SetCredentials(v *CredentialsPayload) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &recordPayload_Credentials{v}
}

func (x *RecordPayload) SetCard(v *CardPayload) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &recordPayload_Card{v}
}

func (x *RecordPayload) SetText(v *TextPayload) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &recordPayload_Text{v}
}

func (x *RecordPayload) SetBinary(v *BinaryPayload) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &recordPayload_Binary{v}
}

func (x *RecordPayload) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *RecordPayload) HasCredentials() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*recordPayload_Credentials)
	return ok
}

func (x *RecordPayload) HasCard() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*recordPayload_Card)
	return ok
}

func (x *RecordPayload) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*recordPayload_Text)
	return ok
}

func (x *RecordPayload) HasBinary() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*recordPayload_Binary)
	return ok
}

func (x *RecordPayload) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *RecordPayload) ClearCredentials() {
	if _, ok := x.xxx_hidden_Value.(*recordPayload_Credentials); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *RecordPayload) ClearCard() {
	if _, ok := x.xxx_hidden_Value.(*recordPayload_Card); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *RecordPayload) ClearText() {
	if _, ok := x.xxx_hidden_Value.(*recordPayload_Text); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *RecordPayload) ClearBinary() {
	if _, ok := x.xxx_hidden_Value.(*recordPayload_Binary); ok {
		x.xxx_hidden_Value = nil
	}
}

const RecordPayload_Value_not_set_case case_RecordPayload_Value = 0
const RecordPayload_Credentials_case case_RecordPayload_Value = 1
const RecordPayload_Card_case case_RecordPayload_Value = 2
const RecordPayload_Text_case case_RecordPayload_Value = 3
const RecordPayload_Binary_case case_RecordPayload_Value = 4

func (x *RecordPayload) WhichValue() case_RecordPayload_Value {
	if x == nil {
		return RecordPayload_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *recordPayload_Credentials:
		return RecordPayload_Credentials_case
	case *recordPayload_Card:
		return RecordPayload_Card_case
	case *recordPayload_Text:
		return RecordPayload_Text_case
	case *recordPayload_Binary:
		return RecordPayload_Binary_case
	default:
		return RecordPayload_Value_not_set_case
	}
}

type RecordPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	Credentials *CredentialsPayload
	Card        *CardPayload
	Text        *TextPayload
	Binary      *BinaryPayload
	// -- end of xxx_hidden_Value
}

func (b0 RecordPayload_builder) Build() *RecordPayload {
	m0 := &RecordPayload{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Credentials != nil {
		x.xxx_hidden_Value = &recordPayload_Credentials{b.Credentials}
	}
	if b.Card != nil {
		x.xxx_hidden_Value = &recordPayload_Card{b.Card}
	}
	if b.Text != nil {
		x.xxx_hidden_Value = &recordPayload_Text{b.Text}
	}
	if b.Binary != nil {
		x.xxx_hidden_Value = &recordPayload_Binary{b.Binary}
	}
	return m0
}

type case_RecordPayload_Value protoreflect.FieldNumber

func (x case_RecordPayload_Value) String() string {
	md := file_api_gopherkeeper_proto_msgTypes[12].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRecordPayload_Value interface {
	isRecordPayload_Value()
}

type recordPayload_Credentials struct {
	Credentials *CredentialsPayload `protobuf:"bytes,1,opt,name=credentials,proto3,oneof"`
}

type recordPayload_Card struct {
	Card *CardPayload `protobuf:"bytes,2,opt,name=card,proto3,oneof"`
}

type recordPayload_Text struct {
	Text *TextPayload `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type recordPayload_Binary struct {
	Binary *BinaryPayload `protobuf:"bytes,4,opt,name=binary,proto3,oneof"`
}

func (*recordPayload_Credentials) isRecordPayload_Value() {}

func (*recordPayload_Card) isRecordPayload_Value() {}

func (*recordPayload_Text) isRecordPayload_Value() {}

func (*recordPayload_Binary) isRecordPayload_Value() {}

type Record struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *RecordMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3"`
	xxx_hidden_Payload  *RecordPayload         `protobuf:"bytes,2,opt,name=payload,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_gopherkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetMetadata() *RecordMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Record) GetPayload() *RecordPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Record) SetMetadata(v *RecordMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Record) SetPayload(v *RecordPayload) {
	x.xxx_hidden_Payload = v
}

func (x *Record) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Record) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *Record) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Record) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *RecordMetadata
	Payload  *RecordPayload
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type CreateRecordRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title   string                 `protobuf:"bytes,1,opt,name=title,proto3"`
	xxx_hidden_Payload *RecordPayload         `protobuf:"bytes,2,opt,name=payload,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRecordRequest) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *CreateRecordRequest) GetPayload() *RecordPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateRecordRequest) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *CreateRecordRequest) SetPayload(v *RecordPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateRecordRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateRecordRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

type CreateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title   string
	Payload *RecordPayload
}

func (b0 CreateRecordRequest_builder) Build() *CreateRecordRequest {
	m0 := &CreateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListRecordsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListRecordsRequest_builder) Build() *ListRecordsRequest {
	m0 := &ListRecordsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListRecordsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*RecordMetadata     `protobuf:"bytes,1,rep,name=records,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_api_gopherkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsResponse) GetRecords() []*RecordMetadata {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *ListRecordsResponse) SetRecords(v []*RecordMetadata) {
	x.xxx_hidden_Records = &v
}

type ListRecordsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*RecordMetadata
}

func (b0 ListRecordsResponse_builder) Build() *ListRecordsResponse {
	m0 := &ListRecordsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *GetRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type GetRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 GetRecordRequest_builder) Build() *GetRecordRequest {
	m0 := &GetRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type UpdateRecordRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3"`
	xxx_hidden_Title            string                 `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Payload          *RecordPayload         `protobuf:"bytes,4,opt,name=payload,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRecordRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *UpdateRecordRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.xxx_hidden_ExpectedRevision
	}
	return 0
}

func (x *UpdateRecordRequest) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *UpdateRecordRequest) GetPayload() *RecordPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *UpdateRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *UpdateRecordRequest) SetExpectedRevision(v int64) {
	x.xxx_hidden_ExpectedRevision = v
}

func (x *UpdateRecordRequest) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *UpdateRecordRequest) SetPayload(v *RecordPayload) {
	x.xxx_hidden_Payload = v
}

func (x *UpdateRecordRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *UpdateRecordRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

type UpdateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
	// expected_revision содержит ревизию записи, которую клиент намерен изменить.
	ExpectedRevision int64
	Title            string
	Payload          *RecordPayload
}

func (b0 UpdateRecordRequest_builder) Build() *UpdateRecordRequest {
	m0 := &UpdateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ExpectedRevision = b.ExpectedRevision
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type DeleteRecordRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_api_gopherkeeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRecordRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *DeleteRecordRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.xxx_hidden_ExpectedRevision
	}
	return 0
}

func (x *DeleteRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *DeleteRecordRequest) SetExpectedRevision(v int64) {
	x.xxx_hidden_ExpectedRevision = v
}

type DeleteRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
	// expected_revision содержит ревизию записи, которую клиент намерен удалить.
	ExpectedRevision int64
}

func (b0 DeleteRecordRequest_builder) Build() *DeleteRecordRequest {
	m0 := &DeleteRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ExpectedRevision = b.ExpectedRevision
	return m0
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_api_gopherkeeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gopherkeeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteRecordResponse_builder) Build() *DeleteRecordResponse {
	m0 := &DeleteRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_gopherkeeper_proto protoreflect.FileDescriptor

const file_api_gopherkeeper_proto_rawDesc = "" +
	"\n" +
	"\x16api/gopherkeeper.proto\x12\x0fgopherkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"g\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\x10RegisterResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.gopherkeeper.v1.UserR\x04user\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x98\x01\n" +
	"\rLoginResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.gopherkeeper.v1.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x14\n" +
	"\x12CurrentUserRequest\"@\n" +
	"\x13CurrentUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.gopherkeeper.v1.UserR\x04user\"\xf9\x01\n" +
	"\x0eRecordMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.gopherkeeper.v1.RecordTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\x12CredentialsPayload\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"\xf1\x01\n" +
	"\vCardPayload\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x1e\n" +
	"\n" +
	"cardholder\x18\x02 \x01(\tR\n" +
	"cardholder\x12>\n" +
	"\fexpiry_month\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\vexpiryMonth\x12<\n" +
	"\vexpiry_year\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"expiryYear\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"=\n" +
	"\vTextPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"i\n" +
	"\rBinaryPayload\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x88\x01\x01\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadataB\a\n" +
	"\x05_data\"\x83\x02\n" +
	"\rRecordPayload\x12G\n" +
	"\vcredentials\x18\x01 \x01(\v2#.gopherkeeper.v1.CredentialsPayloadH\x00R\vcredentials\x122\n" +
	"\x04card\x18\x02 \x01(\v2\x1c.gopherkeeper.v1.CardPayloadH\x00R\x04card\x122\n" +
	"\x04text\x18\x03 \x01(\v2\x1c.gopherkeeper.v1.TextPayloadH\x00R\x04text\x128\n" +
	"\x06binary\x18\x04 \x01(\v2\x1e.gopherkeeper.v1.BinaryPayloadH\x00R\x06binaryB\a\n" +
	"\x05value\"\x7f\n" +
	"\x06Record\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.gopherkeeper.v1.RecordMetadataR\bmetadata\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.gopherkeeper.v1.RecordPayloadR\apayload\"e\n" +
	"\x13CreateRecordRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.gopherkeeper.v1.RecordPayloadR\apayload\"\x14\n" +
	"\x12ListRecordsRequest\"P\n" +
	"\x13ListRecordsResponse\x129\n" +
	"\arecords\x18\x01 \x03(\v2\x1f.gopherkeeper.v1.RecordMetadataR\arecords\"\"\n" +
	"\x10GetRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x01\n" +
	"\x13UpdateRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x03R\x10expectedRevision\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x128\n" +
	"\apayload\x18\x04 \x01(\v2\x1e.gopherkeeper.v1.RecordPayloadR\apayload\"R\n" +
	"\x13DeleteRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x03R\x10expectedRevision\"\x16\n" +
	"\x14DeleteRecordResponse*\x8a\x01\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RECORD_TYPE_CREDENTIALS\x10\x01\x12\x14\n" +
	"\x10RECORD_TYPE_CARD\x10\x02\x12\x14\n" +
	"\x10RECORD_TYPE_TEXT\x10\x03\x12\x16\n" +
	"\x12RECORD_TYPE_BINARY\x10\x042\x80\x02\n" +
	"\vAuthService\x12O\n" +
	"\bRegister\x12 .gopherkeeper.v1.RegisterRequest\x1a!.gopherkeeper.v1.RegisterResponse\x12F\n" +
	"\x05Login\x12\x1d.gopherkeeper.v1.LoginRequest\x1a\x1e.gopherkeeper.v1.LoginResponse\x12X\n" +
	"\vCurrentUser\x12#.gopherkeeper.v1.CurrentUserRequest\x1a$.gopherkeeper.v1.CurrentUserResponse2\xad\x03\n" +
	"\rRecordService\x12M\n" +
	"\fCreateRecord\x12$.gopherkeeper.v1.CreateRecordRequest\x1a\x17.gopherkeeper.v1.Record\x12X\n" +
	"\vListRecords\x12#.gopherkeeper.v1.ListRecordsRequest\x1a$.gopherkeeper.v1.ListRecordsResponse\x12G\n" +
	"\tGetRecord\x12!.gopherkeeper.v1.GetRecordRequest\x1a\x17.gopherkeeper.v1.Record\x12M\n" +
	"\fUpdateRecord\x12$.gopherkeeper.v1.UpdateRecordRequest\x1a\x17.gopherkeeper.v1.Record\x12[\n" +
	"\fDeleteRecord\x12$.gopherkeeper.v1.DeleteRecordRequest\x1a%.gopherkeeper.v1.DeleteRecordResponseB>Z<github.com/xhrobj/gopherkeeper/internal/proto;gopherkeeperpbb\x06proto3"

var file_api_gopherkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gopherkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_gopherkeeper_proto_goTypes = []any{
	(RecordType)(0),               // 0: gopherkeeper.v1.RecordType
	(*User)(nil),                  // 1: gopherkeeper.v1.User
	(*RegisterRequest)(nil),       // 2: gopherkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: gopherkeeper.v1.RegisterResponse
	(*LoginRequest)(nil),          // 4: gopherkeeper.v1.LoginRequest
	(*LoginResponse)(nil),         // 5: gopherkeeper.v1.LoginResponse
	(*CurrentUserRequest)(nil),    // 6: gopherkeeper.v1.CurrentUserRequest
	(*CurrentUserResponse)(nil),   // 7: gopherkeeper.v1.CurrentUserResponse
	(*RecordMetadata)(nil),        // 8: gopherkeeper.v1.RecordMetadata
	(*CredentialsPayload)(nil),    // 9: gopherkeeper.v1.CredentialsPayload
	(*CardPayload)(nil),           // 10: gopherkeeper.v1.CardPayload
	(*TextPayload)(nil),           // 11: gopherkeeper.v1.TextPayload
	(*BinaryPayload)(nil),         // 12: gopherkeeper.v1.BinaryPayload
	(*RecordPayload)(nil),         // 13: gopherkeeper.v1.RecordPayload
	(*Record)(nil),                // 14: gopherkeeper.v1.Record
	(*CreateRecordRequest)(nil),   // 15: gopherkeeper.v1.CreateRecordRequest
	(*ListRecordsRequest)(nil),    // 16: gopherkeeper.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),   // 17: gopherkeeper.v1.ListRecordsResponse
	(*GetRecordRequest)(nil),      // 18: gopherkeeper.v1.GetRecordRequest
	(*UpdateRecordRequest)(nil),   // 19: gopherkeeper.v1.UpdateRecordRequest
	(*DeleteRecordRequest)(nil),   // 20: gopherkeeper.v1.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),  // 21: gopherkeeper.v1.DeleteRecordResponse
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil), // 23: google.protobuf.Int32Value
}
var file_api_gopherkeeper_proto_depIdxs = []int32{
	22, // 0: gopherkeeper.v1.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: gopherkeeper.v1.RegisterResponse.user:type_name -> gopherkeeper.v1.User
	1,  // 2: gopherkeeper.v1.LoginResponse.user:type_name -> gopherkeeper.v1.User
	22, // 3: gopherkeeper.v1.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: gopherkeeper.v1.CurrentUserResponse.user:type_name -> gopherkeeper.v1.User
	0,  // 5: gopherkeeper.v1.RecordMetadata.type:type_name -> gopherkeeper.v1.RecordType
	22, // 6: gopherkeeper.v1.RecordMetadata.created_at:type_name -> google.protobuf.Timestamp
	22, // 7: gopherkeeper.v1.RecordMetadata.updated_at:type_name -> google.protobuf.Timestamp
	23, // 8: gopherkeeper.v1.CardPayload.expiry_month:type_name -> google.protobuf.Int32Value
	23, // 9: gopherkeeper.v1.CardPayload.expiry_year:type_name -> google.protobuf.Int32Value
	9,  // 10: gopherkeeper.v1.RecordPayload.credentials:type_name -> gopherkeeper.v1.CredentialsPayload
	10, // 11: gopherkeeper.v1.RecordPayload.card:type_name -> gopherkeeper.v1.CardPayload
	11, // 12: gopherkeeper.v1.RecordPayload.text:type_name -> gopherkeeper.v1.TextPayload
	12, // 13: gopherkeeper.v1.RecordPayload.binary:type_name -> gopherkeeper.v1.BinaryPayload
	8,  // 14: gopherkeeper.v1.Record.metadata:type_name -> gopherkeeper.v1.RecordMetadata
	13, // 15: gopherkeeper.v1.Record.payload:type_name -> gopherkeeper.v1.RecordPayload
	13, // 16: gopherkeeper.v1.CreateRecordRequest.payload:type_name -> gopherkeeper.v1.RecordPayload
	8,  // 17: gopherkeeper.v1.ListRecordsResponse.records:type_name -> gopherkeeper.v1.RecordMetadata
	13, // 18: gopherkeeper.v1.UpdateRecordRequest.payload:type_name -> gopherkeeper.v1.RecordPayload
	2,  // 19: gopherkeeper.v1.AuthService.Register:input_type -> gopherkeeper.v1.RegisterRequest
	4,  // 20: gopherkeeper.v1.AuthService.Login:input_type -> gopherkeeper.v1.LoginRequest
	6,  // 21: gopherkeeper.v1.AuthService.CurrentUser:input_type -> gopherkeeper.v1.CurrentUserRequest
	15, // 22: gopherkeeper.v1.RecordService.CreateRecord:input_type -> gopherkeeper.v1.CreateRecordRequest
	16, // 23: gopherkeeper.v1.RecordService.ListRecords:input_type -> gopherkeeper.v1.ListRecordsRequest
	18, // 24: gopherkeeper.v1.RecordService.GetRecord:input_type -> gopherkeeper.v1.GetRecordRequest
	19, // 25: gopherkeeper.v1.RecordService.UpdateRecord:input_type -> gopherkeeper.v1.UpdateRecordRequest
	20, // 26: gopherkeeper.v1.RecordService.DeleteRecord:input_type -> gopherkeeper.v1.DeleteRecordRequest
	3,  // 27: gopherkeeper.v1.AuthService.Register:output_type -> gopherkeeper.v1.RegisterResponse
	5,  // 28: gopherkeeper.v1.AuthService.Login:output_type -> gopherkeeper.v1.LoginResponse
	7,  // 29: gopherkeeper.v1.AuthService.CurrentUser:output_type -> gopherkeeper.v1.CurrentUserResponse
	14, // 30: gopherkeeper.v1.RecordService.CreateRecord:output_type -> gopherkeeper.v1.Record
	17, // 31: gopherkeeper.v1.RecordService.ListRecords:output_type -> gopherkeeper.v1.ListRecordsResponse
	14, // 32: gopherkeeper.v1.RecordService.GetRecord:output_type -> gopherkeeper.v1.Record
	14, // 33: gopherkeeper.v1.RecordService.UpdateRecord:output_type -> gopherkeeper.v1.Record
	21, // 34: gopherkeeper.v1.RecordService.DeleteRecord:output_type -> gopherkeeper.v1.DeleteRecordResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_gopherkeeper_proto_init() }
func file_api_gopherkeeper_proto_init() {
	if File_api_gopherkeeper_proto != nil {
		return
	}
	file_api_gopherkeeper_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_gopherkeeper_proto_msgTypes[12].OneofWrappers = []any{
		(*recordPayload_Credentials)(nil),
		(*recordPayload_Card)(nil),
		(*recordPayload_Text)(nil),
		(*recordPayload_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gopherkeeper_proto_rawDesc), len(file_api_gopherkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_gopherkeeper_proto_goTypes,
		DependencyIndexes: file_api_gopherkeeper_proto_depIdxs,
		EnumInfos:         file_api_gopherkeeper_proto_enumTypes,
		MessageInfos:      file_api_gopherkeeper_proto_msgTypes,
	}.Build()
	File_api_gopherkeeper_proto = out.File
	file_api_gopherkeeper_proto_goTypes = nil
	file_api_gopherkeeper_proto_depIdxs = nil
}
