sonar.organization=xhrobj
sonar.projectKey=xhrobj_gophkeeper

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=\
  cmd/**/main.go,\
  internal/logger/**,\
  internal/model/**,\
  migrations/**,\
  **/*_test.go

sonar.exclusions=\
  bin/**,\
  dist/**

# CPD-исключения оставлены здесь для видимости как намерение.
# Фактически они были настроены в UI SonarCloud:
# Project -> Administration -> General settings -> Analysis Scope
sonar.cpd.exclusions=\
  migrations/**,\
  **/*_test.go
