sonar.organization=xhrobj
sonar.projectKey=xhrobj_gophkeeper

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=\
  cmd/**/main.go

sonar.exclusions=\
  bin/**,\
  dist/**
